---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d35f88e690d4d00104f6f3b/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Global Site Config
  templates:
  - config
- type: document
  path: data/author.json
  label: Author
  templates:
  - author
- type: document
  path: data/header.yml
  label: Header
  templates:
  - header
- type: document
  path: data/footer.yml
  label: Footer
  templates:
  - footer
- type: document
  path: data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: data/doc_sections.yml
  label: Documentation Sections
  templates:
  - doc_sections
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: content/blog/_index.md
  label: Blog
  templates:
  - blog
- type: document
  path: content/overview.md
  label: Overview
  templates:
  - overview
- type: document
  path: content/showcase.md
  label: Showcase
  templates:
  - showcase
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{posts/**,_index.md,blog/_index.md,overview.md,showcase.md}"
  templates:
  - page
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.47
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: '0.47'
